### ISSUE TITLE
Change pageRange attributes into get methods

### ISSUE THREAD

**Issue by ariqRam** [ramdhanyA/ankislide#3]
Don't use 
this.writingPageRange,
use 
getWritingPageRange() {
  // do something with this.startingPageRange
}

**Comment by ramdhanyA** [comment]
leaving it as attributes is cleaner as a singular method can't really handle pageRange category cleaner than the current attribute

**Comment by ariqRam** [comment]
leaving it as attributes is cleaner as a singular method can't really handle pageRange category cleaner than the current attribute
